title: Kimi's Website
logo:
description: Thank you for visiting my website!:-)
show_downloads: false
github:
  is_project_page: false
  is_my_page: true
  is_user_page: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
 - jekyll-sitemap
